### PR TITLE
Add different neural network models

### PR DESCRIPTION
**Pull request by GuptaVishu2002**

### CODE REVIEW

**Comment by knc6** [comment]
Hi @GuptaVishu2002 

Thank you for the PR.

Could you please change the filename to `AI-SinglePropertyPrediction-formula_energy-ssub-test-mae.csv` instead of `SinglePropertyPrediction-test-formula_energy-ssub-AI-mae.csv` in line [here](https://github.com/GuptaVishu2002/jarvis_leaderboard/blob/e019dea63d2c63c0c07792f4d537a17c2f2ba2a1/jarvis_leaderboard/contributions/ElemNet1/run.py#L136) and similar files in other contribution folders? You can just rename the files instead of running the calculations again.

There was filename convention change and I think thats what causing an error.

Also, please make this PR to develop branch and not the main branch.

**Comment by GuptaVishu2002** [comment]
Hi @knc6 

I have changed the file name in all the contributed files. Do you also want me to change the filename of the zip files?

Also, I have changed the PR to develop branch.

**Comment by GuptaVishu2002** [comment]
Hi @knc6 

Sorry for the misunderstanding. I have changed the filenames to the specified ones.

**Comment by GuptaVishu2002** [comment]
Thank You, @knc6. Please let me know if the file requires significant changes or if there is anything else that I can contribute to the project.

**Comment by GuptaVishu2002** [comment]
@knc6, at the moment, the predicted values in the `AI-SinglePropertyPrediction-formula_energy-ssub-test-mae.csv` file are in the array format (e.g. [-2.8330874] instead of -2.8330874). Do you think that's what is causing the error during the PR? Thank You.

**Pull request merged**
