### PR TITLE
Pull request for Tiwary Lab contribution

### PR DESCRIPTION
**Pull request by erb24**

### CODE REVIEW

**Comment by erb24** [comment]
Sorry for all the closing and opening of pull requests -- some of the zipped files contained spurious hyphens that I believe were throwing errors.

**Comment by knc6** [comment]
Hi @erb24 
Could you make the PR to the develop branch?

**Comment by erb24** [comment]
Sure; do I have to move the files from the main branch in my fork, or can I submit a pull request between my forked main branch and the develop branch in the parent repository?

**Comment by knc6** [comment]
No worries. Just the destination branch needs to be 'develop' instead of main. Here are the instructions: https://pages.nist.gov/jarvis_leaderboard/#howto

**Comment by erb24** [comment]
Okay; I think the new pull request should be fine then.

**Pull request closed without merging**
